### ISSUE TITLE
crushed when "Splicing in phased SVs"

### ISSUE THREAD

**Issue by yekaizhou** [schatzlab/crossstitch#14]
Hi,

crossstitch will break out in the the stage of `splicing in phased SVs`, using my data of 8X ONT reads-generated BAM, VCF etc. The memory usage was largely beneath the capacity.

**Comment by Ocean-Lyu** [comment]
Hi, thanks for developing crossstitch!
I`m having the same issue, and the final.splice.log file outputs like:

-cat final.spliced.log
Reading phased SNPs
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.base/java.nio.HeapCharBuffer.toString(HeapCharBuffer.java:598)
        at java.base/java.nio.CharBuffer.toString(CharBuffer.java:1506)
        at java.base/java.util.regex.Matcher.toMatchResult(Matcher.java:274)
        at java.base/java.util.Scanner.match(Scanner.java:1399)
        at java.base/java.util.Scanner.nextLine(Scanner.java:1652)
        at PhaseSVs.runSplicing(PhaseSVs.java:194)
        at PhaseSVs.main(PhaseSVs.java:80)

Could you possibly help with this?

**Comment by mschatz** [comment]
You will need to rerun with more memory. For this you will need to edit
crossstitch.sh to increase the memory for the PhaseSV stage with
something like:

java -Xmx400000m  -cp $BINDIR PhaseSVs $PHASEDSNPS $OUTPREFIX.scrubbed.vcf
$OUTPREFIX.hairs $OUTPREFIX.spliced.vcf $GENOME >& $OUTPREFIX.spliced.log

Good luck!
Mike

**Comment by Ocean-Lyu** [comment]
Thanks for your timely reply! My problem is now solved!
